// 界面原型：状态仅保存在内存中，不访问真实账号，不下载远程模型文件。
const icons = {
 cloud:'<path d="M7 18H6a4 4 0 0 1-1-8 7 7 0 0 1 13-2 5 5 0 0 1 0 10h-1M12 12v9m-3-3 3 3 3-3"/>',
 cube:'<path d="m12 3 9 5v8l-9 5-9-5V8Z"/><path d="m3 8 9 5 9-5M12 13v8M7.5 5.5l9 5"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 heart:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 6l-1.1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 folder:'<path d="M3 7V5h7l2 3h9v12H3Z"/>',
 users:'<circle cx="9" cy="8" r="4"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M17 4a4 4 0 0 1 0 8m1 3a6 6 0 0 1 4 6"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 down:'<path d="m6 9 6 6 6-6"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 plus:'<path d="M12 4v16M4 12h16"/>',
 sync:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M5.5 7a7.5 7.5 0 0 1 13-1L20 12M4 12l1.5 6a7.5 7.5 0 0 0 13-1"/>',
 settings:'<path d="m10 3-1 3-3 1-3 3 2 3-1 4 4 1 3 3 3-2 4 1 1-4 2-3-2-3-1-4-4-1Z"/><circle cx="12" cy="12" r="3"/>',
 list:'<path d="M8 5h13M8 12h13M8 19h13M3 5h.1M3 12h.1M3 19h.1"/>',
 link:'<path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m0 4 1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0" transform="translate(2 1)"/>',
 x:'<path d="m6 6 12 12M6 18 18 6"/>',
 file:'<path d="M5 3h9l5 5v13H5Z"/><path d="M14 3v6h5M8 14h8M8 17h5"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 pause:'<path d="M8 5v14M16 5v14"/>',
 play:'<path d="m7 4 14 8-14 8Z"/>',
 drive:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 13h18M16 16h2"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
 external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.cube}</svg>`;
const models=[
 {id:1,title:'旋纹花瓶',en:'Spiral Vase',author:'Layer by Layer',image:'vase',category:'家居装饰',site:'cn',size:24.8,files:3,saved:true,bg:'#e9ede4',desc:'让光影沿着曲线流动。以自然生长的螺旋为灵感，细腻的纵向纹理让这只花瓶在不同光线下呈现柔和的层次。适合书桌、窗台，也适合一束刚刚好大小的干花。',material:'PLA · 亚麻绿',time:'3 小时 20 分钟'},
 {id:2,title:'蘑菇氛围灯',en:'Mushroom Lamp',author:'Studio Forma',image:'lamp',category:'家居装饰',site:'global',size:56.2,files:4,saved:true,bg:'#efebe4',desc:'一盏为角落而生的小灯。褶皱灯罩和圆润底座组成温暖的蘑菇轮廓，可拆分的设计便于组合不同配色。灯罩与底座分件打印，图片为造型设计示意。',material:'PLA · 奶油白',time:'6 小时 45 分钟'},
 {id:3,title:'极简耳机支架',en:'Headphone Stand',author:'Print Practice',image:'stand',category:'桌面收纳',site:'cn',size:18.6,files:2,saved:true,bg:'#e6e9e7',desc:'为桌面留一点呼吸感。简洁的几何支架承托耳机，宽底座提供稳定支撑，顶部弧面减少对头梁的挤压。',material:'PETG · 森林绿',time:'2 小时 50 分钟'},
 {id:4,title:'可动关节小龙',en:'Articulated Dragon',author:'Layer by Layer',image:'dragon',category:'趣味玩具',site:'global',size:42.5,files:2,saved:false,bg:'#e4e9de',desc:'一只可以盘在手心里的小龙。分节造型让身体拥有灵活姿态，适合摆在桌边，随时给日常增加一点乐趣。',material:'PLA · 苔藓绿',time:'4 小时 10 分钟'},
 {id:5,title:'模块化桌面托盘',en:'Everyday Organizer',author:'Print Practice',image:'tray',category:'桌面收纳',site:'cn',size:31.4,files:5,saved:true,bg:'#f1e6df',desc:'给那些总是找不到的小东西一个固定位置。分区收纳钥匙、耳机和文具，低矮的轮廓让桌面保持整洁。',material:'PLA · 陶土橙',time:'3 小时 55 分钟'},
 {id:6,title:'条纹小花盆',en:'Ribbed Planter',author:'Studio Forma',image:'planter',category:'家居装饰',site:'global',size:29.7,files:3,saved:true,bg:'#e9e7df',desc:'一片属于桌面的微型绿洲。竖向纹理搭配柔和的圆角外形，适合小型绿植。模型包含花盆与接水托盘。',material:'PLA · 沙石色',time:'3 小时 15 分钟'},
 {id:7,title:'口袋宇航员',en:'Little Astronaut',author:'Layer by Layer',image:'astronaut',category:'趣味玩具',site:'cn',size:35.2,files:2,saved:false,bg:'#e7e9ec',desc:'把探索宇宙的小小梦想放在桌上。圆润的头盔、迷你的背包和柔和的比例，组成一位安静陪伴你的宇航员。',material:'PLA · 月岩白',time:'4 小时 30 分钟'},
 {id:8,title:'倾角手机支架',en:'Angle Phone Dock',author:'Print Practice',image:'phone',category:'数码配件',site:'global',size:14.9,files:2,saved:false,bg:'#ede5de',desc:'一个刚刚好的观看角度。开放式结构保留充电空间，圆角底托稳稳承接手机，适合书桌与床头。',material:'PLA · 日落橙',time:'1 小时 40 分钟'}
];
const variants=['A','B','C'];
let variant=variants.includes(new URLSearchParams(location.search).get('variant'))?new URLSearchParams(location.search).get('variant'):'A';
let state={page:'library',site:'all',category:'全部',query:'',sort:'recent',layout:'grid',status:'all',author:'all',settingsTab:'accounts',accounts:{cn:true,global:false},tasks:[],detailTab:'intro',selected:null};
const names={library:'模型库',downloads:'下载任务',settings:'设置'};
let modalFocus=null;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3400);}
function navItem(page,name,ico,count){return `<button class="nav-item ${state.page===page?'active':''}" data-page="${page}" aria-label="${name}">${icon(ico)}<span>${name}</span>${count!==undefined?`<small>${count}</small>`:''}</button>`;}
// 导航只承载三个独立模块，来源与下载状态留在模型库内筛选。
function sidebar(){return `<aside class="sidebar"><div class="traffic" aria-label="macOS 窗口装饰"><i></i><i></i><i></i></div><a class="brand" href="./" aria-label="MakerShelf 模型馆首页"><span class="brand-icon">${icon('cube')}</span><span>MakerShelf<small>灵感，有处安放。</small></span></a><div class="nav-label">我的工作空间</div><nav>${navItem('library','模型库','grid',models.length)}${navItem('downloads','下载任务','download',state.tasks.filter(t=>t.progress<100).length||undefined)}${navItem('settings','设置','settings')}</nav><div class="sidebar-sites"><div class="nav-label">站点连接状态</div>${['cn','global'].map(site=>`<div class="site-line"><span class="site-logo ${site==='global'?'global':''}">M</span><span>MakerWorld ${site==='cn'?'中文站':'国际站'}<small>${state.accounts[site]?'演示账号已连接':'未连接 · 前往设置'}</small></span><i class="status-dot ${state.accounts[site]?'online':''}"></i></div>`).join('')}</div><div class="sidebar-bottom"><div class="storage"><span>${icon('drive')}本地资料库 <b>${models.filter(m=>m.saved).reduce((sum,m)=>sum+m.size,0).toFixed(1)} MB</b></span><div class="storage-line"><i></i></div><small>模型、介绍与图片，一起珍藏</small></div><div class="profile"><span class="avatar">C</span><span>我的工作空间<small>本地优先 · 界面演示</small></span></div></div></aside>`;}
function topbar(){return `<header class="topbar"><div class="breadcrumb">我的工作空间 ${icon('chevron')} <b>${names[state.page]}</b></div><div class="topbar-right"><span class="demo-tag"><i></i> 演示模式</span></div></header>`;}
function pageHeading(title,sub,action=true){return `<div class="page-heading"><div><div class="eyebrow">YOUR IDEAS, COLLECTED.</div><h1>${title}<span class="heading-dot">.</span></h1><p>${sub}</p></div>${action?`<div class="heading-actions"><button class="button primary" data-action="import">${icon('plus')}导入模型</button></div>`:''}</div>`;}
function filtered(){return models.filter(m=>(state.site==='all'||m.site===state.site)&&(state.category==='全部'||m.category===state.category)&&(state.status==='all'||(state.status==='saved'?m.saved:!m.saved))&&(state.author==='all'||m.author===state.author)&&`${m.title} ${m.en} ${m.author}`.toLowerCase().includes(state.query.toLowerCase())).sort((a,b)=>state.sort==='name'?a.title.localeCompare(b.title,'zh'):state.sort==='size'?b.size-a.size:a.id-b.id);}
function card(m){return `<article class="model-card"><button class="model-cover" style="--card-bg:${m.bg}" data-detail="${m.id}" aria-label="查看${m.title}"><img src="assets/${m.image}.svg" alt="${m.title}造型示意" draggable="false"><span class="file-badge">${m.files} 个文件</span><span class="cover-open">查看模型 ${icon('arrow')}</span></button><div class="card-content"><div class="card-title-row"><button class="card-title" data-detail="${m.id}">${m.title}</button><span class="format">3MF</span></div><div class="card-author"><span class="mini-avatar" style="--avatar:${m.site==='cn'?'#e4e9dc':'#ede3d9'}">${m.author[0]}</span>${m.author}</div><div class="card-footer"><span class="source"><i class="${m.site}"></i>${m.site==='cn'?'中文站':'国际站'}</span><span class="model-status ${m.saved?'saved':''}">${icon(m.saved?'check':'cloud')} ${m.saved?'已保存到本地':'待下载'}</span></div></div></article>`;}
function filters(){return `<div class="library-toolbar"><div class="site-tabs" role="group" aria-label="按站点筛选">${[['all','全部来源'],['cn','中文站'],['global','国际站']].map(([v,n])=>`<button class="${state.site===v?'active':''}" data-site="${v}">${n}</button>`).join('')}</div><div class="toolbar-controls"><label class="search-box">${icon('search')}<input id="model-search" placeholder="搜索模型、作者…" value="${escapeHtml(state.query)}" aria-label="搜索模型或作者"><kbd>⌘ K</kbd></label><select id="sort" aria-label="模型排序"><option value="recent" ${state.sort==='recent'?'selected':''}>最近添加</option><option value="name" ${state.sort==='name'?'selected':''}>名称排序</option><option value="size" ${state.sort==='size'?'selected':''}>文件大小</option></select><div class="view-toggle"><button class="${state.layout==='grid'?'active':''}" data-layout="grid" title="网格视图">${icon('grid')}</button><button class="${state.layout==='list'?'active':''}" data-layout="list" title="列表视图">${icon('list')}</button></div></div></div><div class="library-facets"><label>下载状态<select id="status-filter" aria-label="下载状态">${[['all','全部状态'],['saved','已下载'],['pending','未下载']].map(([v,n])=>`<option value="${v}" ${state.status===v?'selected':''}>${n}</option>`).join('')}</select></label><label>作者<select id="author-filter" aria-label="作者筛选"><option value="all">全部作者</option>${[...new Set(models.map(m=>m.author))].map(a=>`<option value="${a}" ${state.author===a?'selected':''}>${a}</option>`).join('')}</select></label><button class="text-button" data-action="reset-filters">重置筛选</button></div><div class="category-row"><div>${['全部','家居装饰','桌面收纳','趣味玩具','数码配件'].map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><small id="result-count">共 ${filtered().length} 个模型</small></div>`;}
function empty(title,sub){return `<div class="empty-state">${icon('cube')}<h3>${title}</h3><p>${sub}</p><button class="button" data-action="reset-filters">重置筛选</button></div>`;}
function modelList(items){return `<div class="model-table"><div class="table-head"><span>模型 / 作者</span><span>来源</span><span>大小</span><span>状态</span><span></span></div>${items.map(m=>`<div class="table-row"><button class="table-model" data-detail="${m.id}"><img src="assets/${m.image}.svg" style="background:${m.bg}" alt=""><span><b>${m.title}</b><small>${m.author}</small></span></button><span>${m.site==='cn'?'中文站':'国际站'}</span><span>${m.size} MB</span><span class="${m.saved?'green-text':''}">${m.saved?'已保存':'待下载'}</span><button class="icon-button" data-detail="${m.id}" title="查看模型">${icon('chevron')}</button></div>`).join('')}</div>`;}
function results(){const items=filtered();return !items.length?empty('这里暂时没有模型','试试其他关键词，或者切换来源和分类。'):state.layout==='list'?modelList(items):`<div class="model-grid">${items.map(card).join('')}</div>`;}
function library(){return `${pageHeading('让灵感，留在本地','统一浏览你的模型、介绍和图片。按来源、作者和下载状态快速找到作品。')}<div class="overview"><div>${icon('cube')}<span><b>${models.length}</b> 个模型</span></div><div>${icon('download')}<span><b>${models.filter(m=>m.saved).length}</b> 已保存到本地</span></div><div>${icon('users')}<span><b>3</b> 位创作者</span></div><span class="overview-note">${icon('check')}介绍与图片随模型保存</span></div>${variant==='B'?`<div class="gallery-feature"><div><span class="eyebrow">THE OBJECT EDIT / 001</span><h2>小小物件，<br>装下日常的灵感。</h2><p>从柔和的曲线，到恰到好处的功能。<br>为你的桌面，收藏一点新的可能。</p><button class="button primary" data-detail="1">探索这件作品 ${icon('arrow')}</button></div><button data-detail="1" aria-label="查看旋纹花瓶"><img src="assets/vase.svg" alt="旋纹花瓶"></button><span class="feature-caption">旋纹花瓶 / Layer by Layer</span></div>`:''}${filters()}<div id="model-results">${results()}</div><div class="library-footnote"><span>${icon('drive')}本地模型，随时翻阅</span><span>所有模型与图片均为界面演示素材</span></div>`;}
function downloads(){return `${pageHeading('每一份灵感，都在路上','模型文件、原始介绍与展示图片，在同一个任务中归档。')}<div class="notice">${icon('info')}当前为交互演示：任务进度为模拟，不会连接 MakerWorld 或写入模型文件。</div><div class="queue-summary"><div><strong>${state.tasks.length}</strong>归档任务</div><div><strong>${state.tasks.filter(t=>t.progress<100).length}</strong>等待完成</div><div><strong>${state.tasks.reduce((sum,t)=>sum+models.find(m=>m.id===t.id).size,0).toFixed(1)} <small>MB</small></strong>模型总大小</div><div class="queue-summary-note">${icon('folder')} 模型文件 / 介绍 / 图片</div></div><div class="section-heading"><h2>下载队列 <small>${state.tasks.length}</small></h2><button class="button" data-action="pause-all">${icon('pause')}暂停全部</button></div><div id="tasks">${taskRows()}</div><div class="download-tip">${icon('folder')}保存位置 <span>~/Movies/MakerShelf/模型库</span><button class="text-button" data-preferences="storage">修改</button></div>`;}
function taskRows(){if(!state.tasks.length)return `<div class="download-empty">${icon('download')}<h2>准备好收藏下一份灵感了吗？</h2><p>粘贴模型链接，或导入账号收藏、作者作品。</p><span class="subtle">点击右上角「导入模型」开始</span></div>`;return state.tasks.map(t=>{const m=models.find(m=>m.id===t.id);return `<div class="task-row"><img src="assets/${m.image}.svg" style="background:${m.bg}" alt=""><div class="task-info"><h3>${m.title}<span>${t.progress===100?'演示已完成':t.paused?'已暂停':'模拟下载中'}</span></h3><p>${m.site==='cn'?'中文站':'国际站'} · ${m.files} 个文件 · ${m.size} MB</p><div class="progress-track"><i style="width:${t.progress}%"></i></div><small>${t.progress===100?'模拟归档完成 · ':''}模型文件${t.bundle?.intro?' → 介绍':''}${t.bundle?.images?' → 图片':''}<b>${t.progress}%</b></small></div><button class="icon-button" data-task="${t.id}" ${t.progress===100?'disabled':''} title="${t.paused?'继续任务':'暂停任务'}">${icon(t.progress===100?'check':t.paused?'play':'pause')}</button></div>`}).join('');}
function accounts(){return `<div class="notice">${icon('info')}这是登录流程的界面预览。正式版将通过站点登录页授权，当前不收集账号、密码或登录凭据。</div><div class="account-grid">${['cn','global'].map(site=>`<article class="account-card"><div class="account-card-top"><span class="site-logo ${site==='global'?'global':''}">M</span><span class="pill ${state.accounts[site]?'green':''}">${state.accounts[site]?'演示已连接':'未连接'}</span></div><h2>MakerWorld ${site==='cn'?'中文站':'国际站'}</h2><p>${site==='cn'?'makerworld.com.cn':'makerworld.com'}</p><div class="account-status">${icon('users')} ${state.accounts[site]?'演示用户 · 创作者的小天地':'连接后可同步你的账号收藏'}</div><button class="button ${state.accounts[site]?'':'primary'}" data-login="${site}">${icon(state.accounts[site]?'check':'external')}${state.accounts[site]?'断开演示连接':'预览登录流程'}</button></article>`).join('')}</div><div class="settings-block"><h3>账号与下载的关系</h3><p>下载使用对应站点的登录状态。指定账号和作者用于选择内容来源；能否访问或下载，仍取决于当前登录账号的权限。</p><p>正式版将保留登录过期、内容不可访问和下载失败等独立状态，方便重新登录后继续任务。</p></div>`;}
function preferences(){return `<div class="settings-block"><h3>${icon('folder')}本地存储</h3><label class="setting-row"><span><b>模型库位置</b><small>模型、介绍、封面和展示图片统一存放</small></span><input value="~/Movies/MakerShelf/模型库" id="storage-path" aria-label="演示模型库路径"></label><div class="setting-row"><span><b>保留作者与来源</b><small>归档时固定保留模型出处，方便回访</small></span><span class="pill green">默认包含</span></div></div><div class="settings-block"><h3>${icon('download')}下载偏好</h3><div class="setting-row"><span><b>完整归档</b><small>每次下载固定包含模型文件、介绍与展示图片</small></span><span class="pill green">默认包含</span></div><label class="setting-row"><span><b>文件格式</b><small>优先下载的模型格式</small></span><select id="preferred-format"><option>全部可用格式</option>优先 3MF</option>优先 STL</option></select></label><label class="setting-row"><span><b>并行任务数</b><small>正式版需适配站点允许的下载频率</small></span><select><option>2 个任务</option>1 个任务</option><option>3 个任务</option></select></label></div><button class="button primary" data-action="save-settings">保存演示偏好</button><p class="subtle">仅演示设置交互，刷新页面后恢复默认值。</p>`;}
// 账号连接与本地偏好集中在设置中，避免多个入口分别维护相同功能。
function settings(){return `${pageHeading('设置','管理站点登录，以及本地存储与下载偏好。',false)}<div class="settings-tabs" role="group" aria-label="设置分类">${[['accounts','站点账号'],['preferences','存储与下载']].map(([v,n])=>`<button data-settings-tab="${v}" class="${state.settingsTab===v?'active':''}">${n}</button>`).join('')}</div>${state.settingsTab==='accounts'?accounts():preferences()}`;}
function render(){document.body.dataset.variant=variant;document.querySelector('#variant-label').textContent={A:'A · 本地工作台',B:'B · 灵感画廊',C:'C · 下载控制台'}[variant];const content=state.page==='downloads'?downloads():state.page==='settings'?settings():library();document.querySelector('#app').innerHTML=`${sidebar()}<div class="workspace">${topbar()}<main>${content}</main><footer class="statusbar"><span><i class="status-dot online"></i>本地工作空间 <span class="status-muted">/ 设计预览</span></span><span>MakerShelf <span class="status-muted">· 为每一份创作留一个位置</span></span></footer></div>`;}
function go(page){state.page=page;render();}
function setVariant(delta){variant=variants[(variants.indexOf(variant)+delta+3)%3];const url=new URL(location.href);url.searchParams.set('variant',variant);history.replaceState({},'',url);if(variant==='C')seedConsole();state.page=variant==='C'?'downloads':'library';state.layout=variant==='C'?'list':'grid';render();toast({A:'方案 A：侧栏分类 + 模型网格',B:'方案 B：横向导航 + 大幅作品画廊',C:'方案 C：深色任务控制台 + 下载队列'}[variant]);}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
// 弹窗独立于主界面，提供键盘焦点约束与 Escape 关闭。
function openModal(html,wide=false){modalFocus=document.activeElement;document.querySelector('#overlay-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'detail-modal':''}" role="dialog" aria-modal="true" aria-label="${wide?'模型详情':'导入与账号操作'}"><button class="modal-close icon-button" data-action="close" title="关闭">${icon('x')}</button>${html}</section></div>`;requestAnimationFrame(()=>document.querySelector('.modal input:not([type=checkbox]), .modal button')?.focus());}
function closeModal(){document.querySelector('#overlay-root').innerHTML='';modalFocus?.focus();}
// 链接和用户主页是两种来源；账号、作者、本人收藏复用同一用户导入表单。
let importMode='user';
let importDraft={site:'cn',target:'self',scope:'favorites',value:''};
function importModal(mode='user'){importMode=mode;openModal(`<div class="modal-kicker">COLLECT SOMETHING GREAT</div><h2>导入模型</h2><p class="modal-subtitle">从链接或用户主页获取模型，预览后加入下载队列。</p><div class="import-tabs">${[['user','users','用户主页'],['link','link','模型链接']].map(([v,i,n])=>`<button data-import-mode="${v}" class="${mode===v?'active':''}">${icon(i)}${n}</button>`).join('')}</div><form id="import-form">${mode==='user'?`<label class="field-label" for="import-site">来源站点</label><select id="import-site">${[['cn','MakerWorld 中文站'],['global','MakerWorld 国际站']].map(([v,n])=>`<option value="${v}" ${importDraft.site===v?'selected':''}>${n}</option>`).join('')}</select><label class="field-label" for="import-target">目标用户</label><select id="import-target"><option value="self" ${importDraft.target==='self'?'selected':''}>当前登录账号</option><option value="specified" ${importDraft.target==='specified'?'selected':''}>指定用户（账号 / 作者）</option></select>${importDraft.target==='specified'?`<label class="field-label" for="import-value">用户 ID 或主页链接</label><input id="import-value" required value="${escapeHtml(importDraft.value)}" placeholder="输入账号、作者 ID 或用户主页链接">`:''}<label class="field-label" for="import-scope">获取内容</label><select id="import-scope"><option value="favorites" ${importDraft.scope==='favorites'?'selected':''}>收藏的模型</option><option value="published" ${importDraft.scope==='published'?'selected':''}>发布的模型（作者作品）</option></select><small class="field-hint">选择「当前登录账号 + 收藏的模型」即可同步自己的收藏。指定用户的内容仅在当前账号有访问权限时可获取。</small>`:`<label class="field-label" for="import-value">模型链接</label><input id="import-value" required value="${escapeHtml(importDraft.value)}" placeholder="https://makerworld.com.cn/zh/models/…"><small class="field-hint">自动识别中文站 / 国际站，无需再次选择来源。</small>`}<div class="archive-bundle">${icon('check')}完整归档：模型文件 + 模型介绍 + 展示图片</div><div id="import-error" class="form-error" role="alert"></div><div class="notice small">${icon('info')}界面演示：不读取真实内容，下一步展示示例导入清单。</div><button class="button primary full" type="submit">预览导入清单 ${icon('arrow')}</button></form>`);}
let importChoices=[];
let archiveOptions={intro:true,images:true};
function seedConsole(){if(!state.tasks.length)state.tasks=[{id:4,progress:62,paused:true,bundle:{intro:true,images:true}},{id:7,progress:24,paused:true,bundle:{intro:true,images:true}}];}
function previewImport(event){event.preventDefault();archiveOptions={intro:true,images:true};let site=importDraft.site;const value=document.querySelector('#import-value')?.value.trim()||'';if(importMode==='link'){try{const url=new URL(value);if(!['makerworld.com','www.makerworld.com','makerworld.com.cn','www.makerworld.com.cn'].includes(url.hostname)||!/^https?:$/.test(url.protocol)||!url.pathname.includes('/models/'))throw Error();site=url.hostname.endsWith('.cn')?'cn':'global';}catch{document.querySelector('#import-error').textContent='请输入有效的 MakerWorld 模型链接（需包含 /models/）。';return;}}else if(importDraft.target==='specified'&&!value){document.querySelector('#import-error').textContent='请先输入目标用户 ID 或主页链接。';return;}if(!state.accounts[site]){document.querySelector('#import-error').innerHTML=`${site==='cn'?'中文站':'国际站'}尚未连接。<button type="button" class="text-button" data-inline-login="${site}">连接演示账号</button>`;return;}importChoices=models.filter(m=>m.site===site).slice(0,importMode==='link'?1:3);openModal(`<div class="modal-kicker">READY TO COLLECT</div><h2>确认你的归档清单</h2><p class="modal-subtitle">${importMode==='link'?'模型链接':`${importDraft.target==='self'?'当前登录账号':'指定用户'} · ${importDraft.scope==='favorites'?'收藏的模型':'发布的模型'}`} · ${site==='cn'?'中文站':'国际站'}<br>以下为固定示例，并非真实解析结果。</p><div class="preview-items">${importChoices.map(m=>`<label class="preview-item"><input type="checkbox" value="${m.id}" checked class="preview-check"><img src="assets/${m.image}.svg" style="background:${m.bg}" alt=""><span><b>${m.title}</b><small>${m.files} 个文件 · ${m.size} MB ${m.saved?'· 已有本地示例，将模拟重新下载':''}</small></span></label>`).join('')}</div><div class="notice small">${icon('info')}归档内容：模型文件${archiveOptions.intro?' + 模型介绍':''}${archiveOptions.images?' + 展示图片':''}。不会写入真实文件。</div><button class="button primary full" data-action="confirm-import">${icon('download')}加入演示队列</button>`);}
function addTasks(ids){let added=0;ids.forEach(id=>{const existing=state.tasks.find(t=>t.id===id);if(existing&&existing.progress<100)return;if(existing)state.tasks=state.tasks.filter(t=>t.id!==id);state.tasks.push({id,progress:0,paused:false,bundle:{...archiveOptions}});added++;});closeModal();go('downloads');toast(added?`${added} 个模型已加入演示队列`:'所选模型已在队列中');}
function detail(id,tab='intro'){const m=models.find(m=>m.id===id);state.selected=id;state.detailTab=tab;openModal(`<div class="detail-layout"><div class="detail-visual" style="background:${m.bg}"><span class="detail-visual-label">MODEL COLLECTION / ${String(m.id).padStart(3,'0')}</span><img id="detail-image" src="assets/${m.image}.svg" alt="${m.title}造型示意"><div class="image-thumbs"><button data-angle="front" class="active" aria-label="完整造型"><img src="assets/${m.image}.svg" alt="完整造型"></button><button data-angle="zoom" aria-label="局部纹理放大"><img src="assets/${m.image}.svg" style="transform:scale(1.6)" alt="局部放大"></button></div><span class="illustration-note">原创造型示意 · 非真实商品照片</span></div><div class="detail-content"><div class="eyebrow">${m.site==='cn'?'MAKERWORLD 中文站':'MAKERWORLD 国际站'}</div><h2>${m.title}</h2><div class="detail-en">${m.en}</div><div class="detail-author"><span class="mini-avatar">${m.author[0]}</span>${m.author}<span class="pill">${m.category}</span></div><div class="detail-stats"><span><b>${m.files}</b>模型文件</span><span><b>${m.size}<small> MB</small></b>文件大小</span><span><b>${m.saved?'已归档':'待下载'}</b>本地状态</span></div><div class="detail-tabs">${[['intro','作品介绍'],['files','模型文件'],['archive','归档信息']].map(([v,n])=>`<button class="${tab===v?'active':''}" data-detail-tab="${v}">${n}</button>`).join('')}</div><div class="detail-tab-content">${tab==='intro'?`<h3>关于这个设计</h3><p>${m.desc}</p><div class="print-info"><span>示意材料 <b>${m.material}</b></span><span>预估打印 <b>${m.time}</b></span></div><small class="subtle">材料与打印时间均为示例，正式版以作者提供的信息为准。</small>`:tab==='files'?Array.from({length:m.files},(_,i)=>`<div class="file-row">${icon('file')}<span>${m.image}${i?'_part'+i:''}.${i%2?'stl':'3mf'}<small>示例文件 · ${i%2?'几何模型':'打印配置'}</small></span><span class="format">${i%2?'STL':'3MF'}</span></div>`).join(''):`<div class="archive-info"><p>${icon('check')}原始介绍与作者信息</p><p>${icon('check')}封面与展示图片</p><p>${icon('check')}来源站点与下载时间</p><small>预设目录：作者 / 模型名称 / 模型文件、图片、介绍</small><p class="subtle">此处展示归档结构，当前没有真实本地文件。</p></div>`}</div><div class="detail-actions">${m.saved?`<span class="archive-bundle">${icon('check')}已归档 · 可在上方查看模型文件与归档信息</span>`:`<button class="button primary" data-download="${m.id}">${icon('download')}下载此模型</button>`}</div><div class="detail-footnote">${icon('info')}保留原作者信息与作品来源</div></div></div>`,true);}
// 统一分发按钮动作，避免原型重复渲染后丢失事件绑定。
document.addEventListener('click',event=>{const b=event.target.closest('button,[data-page]');if(!b){if(event.target.classList.contains('modal-backdrop'))closeModal();return;}const d=b.dataset;if(d.page){go(d.page);return;}if(d.settingsTab){state.settingsTab=d.settingsTab;render();return;}if(d.preferences){state.settingsTab='preferences';go('settings');return;}if(d.detail){detail(Number(d.detail));return;}if(d.site){state.site=d.site;render();return;}if(d.category){state.category=d.category;render();return;}if(d.layout){state.layout=d.layout;render();return;}if(d.importMode){if(d.importMode!==importMode)importDraft.value='';importModal(d.importMode);return;}if(d.inlineLogin){state.accounts[d.inlineLogin]=true;document.querySelector('#import-error').textContent='演示账号已连接，可以继续预览。';render();return;}if(d.login){if(state.accounts[d.login]){state.accounts[d.login]=false;render();toast('演示连接已断开');}else{openModal(`<div class="modal-kicker">CONNECT YOUR WORLD</div><h2>连接${d.login==='cn'?'中文站':'国际站'}</h2><p class="modal-subtitle">正式版将在独立窗口打开 MakerWorld 登录页，由你直接完成登录。</p><div class="login-illustration">${icon('globe')}<span>MakerShelf ${icon('link')} MakerWorld</span></div><div class="notice small">${icon('info')}原型不会打开真实登录页，也不获取你的账号凭据。</div><button class="button primary full" data-connect="${d.login}">模拟登录成功</button>`);}return;}if(d.connect){state.accounts[d.connect]=true;closeModal();render();toast('演示账号已连接');return;}if(d.detailTab){detail(state.selected,d.detailTab);return;}if(d.angle){document.querySelector('#detail-image').style.transform=d.angle==='zoom'?'scale(1.5)':'scale(1)';document.querySelectorAll('[data-angle]').forEach(el=>el.classList.toggle('active',el===b));return;}if(d.download){const m=models.find(m=>m.id===Number(d.download));if(m.saved){detail(m.id,'archive');return;}if(!state.accounts[m.site]){closeModal();state.settingsTab='accounts';go('settings');toast('请先连接模型所属站点的演示账号');return;}archiveOptions={intro:true,images:true};addTasks([m.id]);return;}if(d.task){const task=state.tasks.find(t=>t.id===Number(d.task));task.paused=!task.paused;render();return;}switch(d.action){case 'import':importDraft={site:'cn',target:'self',scope:'favorites',value:''};importModal();break;case 'close':closeModal();break;case 'confirm-import':{const ids=[...document.querySelectorAll('.preview-check:checked')].map(el=>Number(el.value));if(!ids.length){toast('请至少选择一个模型');break;}addTasks(ids);break;}case 'pause-all':state.tasks.forEach(t=>{if(t.progress<100)t.paused=true;});render();toast('所有演示任务已暂停');break;case 'reset-filters':state.query='';state.site='all';state.category='全部';state.status='all';state.author='all';render();break;case 'save-settings':toast('演示偏好已确认，当前不写入磁盘');break;}});
document.addEventListener('input',event=>{if(event.target.id==='import-value')importDraft.value=event.target.value;if(event.target.id==='model-search'){state.query=event.target.value;document.querySelector('#model-results').innerHTML=results();document.querySelector('#result-count').textContent=`共 ${filtered().length} 个模型`;}});
document.addEventListener('change',event=>{const id=event.target.id,value=event.target.value;if(id==='sort'){state.sort=value;render();}else if(id==='status-filter'){state.status=value;render();}else if(id==='author-filter'){state.author=value;render();}else if(id==='import-target'){importDraft.target=value;importModal(importMode);}else if(id==='import-site'){importDraft.site=value;}else if(id==='import-scope'){importDraft.scope=value;}});
document.addEventListener('submit',event=>{if(event.target.id==='import-form')previewImport(event);});
document.addEventListener('keydown',event=>{const modal=document.querySelector('.modal');if(event.key==='Escape'){closeModal();return;}if(modal&&event.key==='Tab'){const nodes=[...modal.querySelectorAll('button:not(:disabled),input:not(:disabled),select,a[href]')];const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}return;}if(modal)return;if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();document.querySelector('#model-search')?.focus();}if(event.target.closest('input,textarea,select,[contenteditable],button'))return;if(event.key==='ArrowLeft')setVariant(-1);if(event.key==='ArrowRight')setVariant(1);});
document.querySelector('#previous-variant').onclick=()=>setVariant(-1);document.querySelector('#next-variant').onclick=()=>setVariant(1);document.querySelector('#variant-label').onclick=()=>setVariant(1);
// 仅用于展示队列状态变化，不执行网络请求或真实文件保存。
setInterval(()=>{let changed=false;let completed=false;state.tasks.forEach(t=>{if(!t.paused&&t.progress<100){t.progress=Math.min(100,t.progress+4);changed=true;if(t.progress===100){completed=true;models.find(m=>m.id===t.id).saved=true;toast('所选内容已完成演示归档');}}});if(completed)render();else if(changed&&state.page==='downloads')document.querySelector('#tasks').innerHTML=taskRows();},900);
if(variant==='C'){seedConsole();state.page='downloads';state.layout='list';}
render();
